// <auto-generated />
namespace BankOfBIT_BC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class testing_transactions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testing_transactions));
        
        string IMigrationMetadata.Id
        {
            get { return "202302231952082_testing_transactions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
