// <auto-generated />
namespace BankOfBIT_BC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class transaction_bankaccountid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transaction_bankaccountid));
        
        string IMigrationMetadata.Id
        {
            get { return "202302232001361_transaction_bankaccountid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
