// <auto-generated />
namespace BankOfBIT_BC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class next_number : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(next_number));
        
        string IMigrationMetadata.Id
        {
            get { return "202302231927233_next_number"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
